export default defineAppConfig({
  pages: [
    'pages/discover/index',
    'pages/match/index',
    'pages/publish/index',
    'pages/venue/index',
    'pages/profile/index',
    'pages/post-detail/index',
    'pages/match-detail/index',
    'pages/venue-detail/index',
    'pages/rate/index',
    'pages/rating-history/index',
    'pages/edit-profile/index',
    'pages/my-matches/index',
    'pages/my-favorites/index',
    'pages/achievements/index',
    'pages/sports-data/index',
    'pages/settings/index',
    'pages/messages/index',
  ],
  tabBar: {
    color: '#B2BEC3',
    selectedColor: '#7EB8DA',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/discover/index', text: '发现', iconPath: 'assets/tabbar/discover.png', selectedIconPath: 'assets/tabbar/discover-active.png' },
      { pagePath: 'pages/match/index', text: '约球', iconPath: 'assets/tabbar/match.png', selectedIconPath: 'assets/tabbar/match-active.png' },
      { pagePath: 'pages/publish/index', text: '发布', iconPath: 'assets/tabbar/publish.png', selectedIconPath: 'assets/tabbar/publish-active.png' },
      { pagePath: 'pages/venue/index', text: '场馆', iconPath: 'assets/tabbar/venue.png', selectedIconPath: 'assets/tabbar/venue-active.png' },
      { pagePath: 'pages/profile/index', text: '我的', iconPath: 'assets/tabbar/profile.png', selectedIconPath: 'assets/tabbar/profile-active.png' },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#FFFFFF',
    navigationBarTitleText: '约球吧',
    navigationBarTextStyle: 'black',
    backgroundColor: '#FAF9F7',
  },
})
